spring:
  config:
    activate:
      on-profile: docker
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
      group-id: payment-group            # Consumer Group ID
      auto-offset-reset: earliest        # earliest or latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: record                   # 수동 커밋 전략 필요시 manual or manual_immediate
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: ${KAFKA_SERVER}
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 12000
        request.timeout.ms: 3000
        retry.backoff.ms: 500
      retries: 5

payment:
  host: localhost
  port: 8080
  endpoint:
    update_event: '/api/v1/payments/event-status'

kafka:
  topics:
    wallet-reply: 'wallet-reply'